[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"

# plugins
plug "zsh-users/zsh-autosuggestions"
plug "hlissner/zsh-autopair"
plug "zap-zsh/supercharge"
plug "zap-zsh/vim"
plug "zsh-users/zsh-syntax-highlighting"

# source
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"
plug "$HOME/.config/zsh/functions.zsh"

autoload edit-command-line; zle -N edit-command-line
# keybinds
bindkey '^ ' autosuggest-accept
bindkey -M vicmd ' ' edit-command-line

# export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.bin":$PATH

export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"
export BUN_INSTALL="$HOME/.bun" 
export PATH="$BUN_INSTALL/bin:$PATH"

if command -v bat &> /dev/null; then
  alias cat="bat -pp"
fi


# bun completions
[ -s "/Users/rubenmate/.bun/_bun" ] && source "/Users/rubenmate/.bun/_bun"
