--
--     ██████╗ ██████╗ ██╗      ██████╗ ██████╗
--    ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗
--    ██║     ██║   ██║██║     ██║   ██║██████╔╝
--    ██║     ██║   ██║██║     ██║   ██║██╔══██╗
--    ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║
--     ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝
--███████╗ ██████╗██╗  ██╗███████╗███╗   ███╗███████╗
--██╔════╝██╔════╝██║  ██║██╔════╝████╗ ████║██╔════╝
--███████╗██║     ███████║█████╗  ██╔████╔██║█████╗
--╚════██║██║     ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝
--███████║╚██████╗██║  ██║███████╗██║ ╚═╝ ██║███████╗
--╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝
--
-- vim.g.tokyonight_style = "day"
-- vim.g.tokyonight_italic_functions = true
-- vim.g.tokyonight_sidebars = { "qf", "vista_kind", "terminal", "packer" }
-- vim.g.tokyonight_day_brightness = 0.5
--
-- -- Change the "hint" color to the "orange" color, and make the "error" color bright red
-- vim.g.tokyonight_colors = { hint = "orange", error = "#ff0000" }
--
-- -- Load the colorscheme
-- vim.cmd [[colorscheme tokyonight]]
-- Lua
vim.g.catppuccin_flavour = "latte" -- latte, frappe, macchiato, mocha
vim.cmd [[colorscheme catppuccin]]
