---
- name: Install
  community.general.homebrew:
    name:
      - git
    state: present

- name: Symlink gitconfig
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.gitconfig"
    src: "{{ ansible_user_dir }}/.dotfiles/roles/git/files/gitconfig"
    state: link

- name: Symlink gitignore_global
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    src: "{{ ansible_user_dir }}/.dotfiles/roles/git/files/gitignore_global"
    state: link
