---
- name: Symlink bin folder
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.bin"
    src: "{{ ansible_user_dir }}/.dotfiles/roles/bin/files/bin"
    state: link

- name: Symlink dotfiles script 
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.bin/dotfiles"
    src: "{{ ansible_user_dir }}/.dotfiles/bin/dotfiles"
    state: link
