# Export dotfiles directory
export DOTFILES="$HOME/.dotfiles"
# XDG PATHS
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# ZSH config dir
export ZDOTDIR=$HOME/.config/zsh

function exists() {
  # `command -v` is similar to `which`
  # https://stackoverflow.com/a/677212/1341838
  command -v $1 >/dev/null 2>&1

  # More explicitly written:
  # command -v $1 1>/dev/null 2>/dev/null
}
. "$HOME/.cargo/env"
