---
- name: Symlink folder
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/tmux"
    src: "{{ ansible_user_dir }}/.dotfiles/roles/tmux/files/tmux"
    state: link
    force: yes
  when: ansible_os_family == "Darwin"

