no_call_parentheses = true
indent_type = 'Spaces'
indent_width = 4
column_width = 100

# This are the default values
# column_width = 120
# line_endings = "Unix"
# indent_type = "Tabs"
# indent_width = 4
# quote_style = "AutoPreferDouble"
# call_parentheses = "Always"
