---
- name: Symlink config
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    src: "{{ ansible_user_dir }}/.dotfiles/roles/starship/files/starship.toml"
    state: link
